before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Ei2PesND0OtzAEFWF2xOUrmFPNVXrODnkLNCik2WhmJ/xyk7iX44oFmtjUQdGYMa6a2Bj0KEib4Ns28yb2kSnYw9K2VBTWHwwr9pJN1f9gUmjKu9vgSlOKuXhUybbQrELg8fFXugs45N+M9gmSdBgXYvIsywVvY/5PXttuHrpeEH6bU3HVjmWJ5k5z4/yj9KL58t041TQ8ezdfGDeKKDtq7cYBXeqbXI247kvt7lrbEARg7ZeAeEbq1fDAP7o923q5pjhar++QaUEj08Nc/tL6lJSl+nVitGVHb64EG+Q08J+n06fQEt2Y+mqWiuVOOWqP7EYQjZr7BizDUxjoK0IEOQ+Qz039Zg/SKtjQO8wrmLnGX6MdpZOSd0nQ4yO3AYqyfh1Nr5J+OzLaIzD7pjUFCvuyCe+ELv4oOUtyo7pVszc7YzZRdc/1xI4sVssfqvECIftP8Gjls1qDyShz8MDMlYaJqDZ7cvtvA4VJZy/roOXi92LHe4MjYaL9INronGIK88elz0golaHy9LOwPw+ZqJ7bDXSntaaOiG+Yw0e1/cIjfSYLmeTgtiDR5ozDa90rQChEjfGwkSa1pPCyaDZSj7us/nZUlt7KDeaD8kE+RstVoewzDDnoMzi32tC5xyQqZ2D0u5IPD8xnw+3bGOdkixOMO5sfgZCm04PUaDZ0g= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
